dist: trusty
sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test
  - npm run lint
  - npm run build -- --prod
  - mv dist/pokecart/index.html dist/pokecart/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pokecart
  on:
    branch: master
