dist: trusty
sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test
  - npm run lint
  - npm run build -- --base-href /yey-jest/
  - mv dist/yey-jest/index.html dist/yey-jest/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/yey-jest
  on:
    branch: master
