dist: trusty
sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - ./node_modules

install:
  - npm run docker:build
  - npm run docker:npm:install

script:
  - npm run docker:npm:run -- lint
  - npm run docker:npm:run -- test
  - npm run docker:npm:run -- test:snapshot
  - npm run e2e
  - npm run build -- --prod --base-href /pokecart/
  - mv dist/pokecart/index.html dist/pokecart/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pokecart
  on:
    branch: master
