dist: trusty
sudo: false

language: node_js
node_js:
  - "stable"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ./node_modules
    - ~/.cache/Cypress

install:
  - npm run docker:build
  - npm run docker:npm:install
  - npx cypress install

script:
  - npm run test:cy:e2e
  - npm run docker:npm:run -- lint
  - npm run docker:npm:run -- test
  - npm run docker:npm:run -- test:snapshot
  - npm run docker:npm:run -- test:e2e
  - npm run build -- --prod --base-href /pokecart/
  - cp dist/pokecart/index.html dist/pokecart/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pokecart
  on:
    branch: master
